routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/////Start of Customer Location //////
//Front End homepage 
Route::get('/', 'IndexController@index')->name('home_page');
///About us page///
Route::get('/about', 'IndexController@about')->name('about');
//Service page
Route::get('/service', 'IndexController@service')->name('service_page');


////->middleware('verified')

////User Login and Register///
Auth::routes(['verify' => true]);
Route::get('/u/register', 'UsersController@create')->name('user_register');
Route::post('/u_register', 'UsersController@store',['verify' => true])->name('u_register')->middleware('verified');

Route::get('/u/login', 'UsersController@Index')->name('user_login');
Route::post('/u_login', 'UsersController@login',['verify' => true])->name('u_login');
Route::get('/u/logout', 'UsersController@logout')->name('user_logout');

// Route::match(['get','post'],'forget-password','UsersController@forgotPassword')->name('password.request');
//social login / facebook socialite
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider',['verify' => true]);
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

//social login with google socialite
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

//Shop Area////////////
Route::resource('/shop', 'ShopController');
Route::get('/product-detail/{id}','ShopController@detailproduct');
Route::get('/get-product-attr','ShopController@getAttrs');

///Search Product Area///
Route::post('/search','ShopController@search')->name('search');

/////Product Filter of Shop Sidebar////
Route::match(['get','post'],'/products-filter','ShopController@filterproduct');

//Get product Attribute price /////
Route::get('/get-product-price','ProductController@getProductPrice');
Route::get('/get-product-qty','ProductController@getProductQty');


//product review///
Route::post('/productReview','ProductReviewController@store')->name('productReview');


/////Cart Area /////
Route::post('/addToCart','CartController@addToCart')->name('addToCart');
Route::get('/viewcart','CartController@index');
Route::get('/resetCart','CartController@resetCart')->name('resetCart');
Route::get('/cart/update-quantity/{id}/{quantity}','CartController@updateQuantity');
Route::get('/cart/deleteItem/{id}','CartController@deleteItem');

//////Apply Coupon /////
Route::post('/cart/apply-coupon','CartController@applyCoupon');


Route::group(['middleware'=>['frontLogin']],function (){

    ////Customer Account Area //////
    Route::get('/account', 'UsersController@account')->name('user_account');
    Route::get('/update-profile', 'UsersController@edit')->name('update_profile');
    Route::post('/update-profile/{id}', 'UsersController@updateprofile')->name('update');
    Route::get('/u/update-password/', 'UsersController@showpassword')->name('change_p');
    Route::post('/update-password/{id}', 'UsersController@updatepassword')->name('update_p');

    //Wish list Area ////
    Route::get('/my-wish-list/', 'CartController@wishList')->name('wish_list');
    Route::get('/wish-list/delete-product/{id}','CartController@deleteWishListProducts');
    
    ///Contact Us Page ///
    Route::resource('/contact','ContactController');
    //Order Area///
    Route::get('/pay_offline', 'UsersController@payoffline')->name('pay_offline');
    Route::get('/check-out','CheckOutController@index');
    Route::post('/submit-checkout','CheckOutController@submitcheckout');
    Route::get('/order-review','OrderController@orderReview');
    Route::post('/submit-order','OrderController@order');
    Route::get('/cod','OrderController@cod');
    Route::get('/paypal','OrderController@paypal');
    Route::get('/pay','OrderController@pay');
    //paypal thanks page
    Route::get('/paypal/thanks','OrderController@thanksPaypal');
    //paypal cancel page
    Route::get('/paypal/cancel','OrderController@cancelPaypal');
    ////User Ordered Product Page
    Route::get('/orders/{id}','OrderController@userOrderDetails');
    

});


////End of Customer Location //////////


///////* Admin Location *///////
Auth::routes(['u_register'=>false,'verify'=>true]);
// Route::get('/home', 'HomeController@index')->name('home');
// Route::resource('admin/product','ProductController');

Route::group(['prefix'=>'admin','middleware'=>['auth','verified','checkAdmin']],function (){

    // Dashboard Area////
    Route::get('/', 'AdminController@index')->name('admin_home');
    Route::resource('/createuser', 'AdminController');
    Route::get('/showuser/', 'AdminController@showallusers')->name('show_user');
    Route::post('/showuser','AdminController@userSearch')->name('user.search');
    Route::get('/profile_update', 'AdminController@edit')->name('profile_update');
    Route::get('/order', 'OrderController@userOrder')->name('order');
    Route::post('/order', 'OrderController@searchOrder')->name('admin.search.order');

    //Admin Order Charts Route
    Route::get('/view-user-charts','AdminController@viewUserCharts');
    Route::get('delete-user/{id}','AdminController@destroy');

    ///Roles Area//////
    Route::resource('/role','RoleController');
    Route::resource('/roleuser','RoleUserController');

    
    
    
    //category Area
    Route::resource('/category','CategoryController');
    Route::get('delete-category/{id}','CategoryController@destroy');
    Route::get('/check_category_name','CategoryController@checkCateName');
    
    ///slider Area
    Route::resource('/slide','SlideController');
    Route::get('delete-slide/{id}','SlideController@destroy');
    Route::get('/check_slide_name','SlideController@checkSlideName');
    
    //Manufacturer or brands Area////
    Route::resource('/manufacturer','ManufacturerController');
    Route::get('delete-brand/{id}','ManufacturerController@destroy');
    
    //Product Category Area///
    Route::resource('/productcategory','ProductCategoryController');
    Route::get('delete-productcategory/{id}','ProductCategoryController@destroy');
    
    ///Box Section Area/////
    Route::resource('/box','BoxSectionController');
    Route::get('delete-box/{id}','BoxSectionController@destroy');
    
    ///Products Area///
    Route::resource('/product','ProductController');
    Route::get('delete-product/{id}','ProductController@destroy');
    Route::post('/products','ProductController@searchProducts')->name('product.search');
    
    
    ///Bundles Area///
    Route::get('/bundle','BundleController@create_bundle');
    Route::get('/bundles','BundleController@index');
    
    
    /// Product Attribute Area/////
    Route::resource('/product_attr','ProductAtrrController');
    Route::get('delete-attribute/{id}','ProductAtrrController@deleteAttr');
    
    /// Product Images Gallery///
    Route::resource('/image-gallery','ImagesController');
    Route::get('delete-imageGallery/{id}','ImagesController@destroy');
    
    ////Relation Area///
    Route::resource('/relation','RelationController');
    Route::get('delete-relation/{id}','RelationController@destroy');
    
    ///Coupon Area ////
    Route::resource('/coupon','CouponController');
    Route::get('delete-coupon/{id}','CouponController@destroy');
    
    ///View Orders Area////
    Route::resource('/orders','OrderController');
    Route::get('/admin/view-orders', 'OrderController@viewOrders');
    Route::get('/orders-invoice/{id}','OrderController@viewOrderInvoice')->name('order.invoice');
    Route::get('delete-order/{id}','OrderController@destroy');
    
    
    ///////Report Area /////// 
    Route::resource('/report','ReportController');
    Route::get('admin/reprot/show','ReportController@show');
    Route::get('/view-order-charts','ReportController@viewOrderCharts');
    Route::post('/report/check','ReportController@checkReport');

    ///Review Area/////
    Route::resource('/customer-reviews','ProductReviewController');
    Route::get('delete-customer-reviews/{id}','ProductReviewController@destroy');











    




});

app/ProductCategory.php
<?php

namespace App;
use Illuminate\Support\Facades\DB;

use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model
{
    //
    protected $table='product_categories';
    protected $primaryKey='id';
    protected $fillable=['p_cat_name','p_cat_top','p_cat_image'];


    public function products(){

        return $this->hasMany(Product::class);
    }

    public static function countProductCategory(){

        $countProductCategory = DB::table('product_categories')->count();

        return $countProductCategory;
    }
}

app/Http/Controllers/ProductCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ProductCategory;
use Intervention\Image\Facades\Image;
class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $menu_active=0;
       
        $p_cats = ProductCategory::all();
        return view('backEnd.productcategories.index',compact('menu_active','p_cats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        $menu_active=2;

        return view('backEnd.productcategories.create',compact('menu_active'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = request()->validate([
            'p_cat_name'=>'required|max:255|unique:product_categories,p_cat_name',
            'p_cat_top'=>'required',
            'p_cat_image' => ['required','image'],
        ]);
        $p_cat_imagePath = request('p_cat_image')->store('PCategoryUploads','public');
        $p_cat_image = Image::make(public_path("storage/{$p_cat_imagePath}"));
        $p_cat_image->save();
        // $data=$request->all();

        ProductCategory::create([
            'p_cat_name' => $data['p_cat_name'],
            'p_cat_top' => $data['p_cat_top'],
            'p_cat_image' => $p_cat_imagePath,


        ]);
        return redirect()->route('productcategory.index')->with('message','Product Category Added Successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $menu_active=0;
       
        $edit_p_cat=ProductCategory::findOrFail($id);
        return view('backEnd.productcategories.edit',compact('edit_p_cat','menu_active'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $menu_active=0;

        $update_p_cat = ProductCategory::findOrFail($id);

        $this->validate($request,[
        
            'p_cat_name'=>'required|max:255',
            'p_cat_top'=>'required',
            'p_cat_image' => ['required','image'],
        ]);

        // dd($request->all());

        $p_cat_imagePath = request('p_cat_image')->store('PCategoryUploads','public');
        $p_cat_image = Image::make(public_path("storage/{$p_cat_imagePath}"));
        $p_cat_image->save();
        $data=$request->all();

        $update_p_cat->update([
            'p_cat_name' => $data['p_cat_name'],
            'p_cat_top' => $data['p_cat_top'],
            'p_cat_image' => $p_cat_imagePath,
        ]);
        return redirect()->route('productcategory.index')->with('message','Product Category Updated Successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $delete=ProductCategory::findOrFail($id);
        $delete->delete();
        return redirect()->route('productcategory.index')->with('message','Product Category Deleted Successfully');
    }
}

resources/views/backEnd/productcategories/create.blade.php
@extends('backEnd.layouts.master')
@section('title','Add Product Category')
@section('content')

<div class="container">


<div class="row"><!-- 1 row Starts -->

<div class="col-lg-12"><!-- col-lg-12 Starts -->

<ol class="breadcrumb"><!-- breadcrumb Starts -->

<li>

<i class="fa fa-dashboard"></i> Dashboard / Insert Products Category

</li>

</ol><!-- breadcrumb Ends -->

</div><!-- col-lg-12 Ends -->

</div><!-- 1 row Ends -->

<div class="row"><!-- 2 row Starts -->

<div class="col-lg-12"><!-- col-lg-12 Starts -->

<div class="panel panel-default"><!-- panel panel-default Starts -->

<div class="panel-heading" ><!-- panel-heading Starts -->

<h3 class="panel-title" ><!-- panel-title Starts -->

<i class="fa fa-money fa-fw" ></i> Insert Product Category

</h3><!-- panel-title Ends -->


</div><!-- panel-heading Ends -->


<div class="panel-body" ><!-- panel-body Starts -->

<form class="form-horizontal" action="{{route('productcategory.store')}}" method="post" enctype="multipart/form-data" ><!-- form-horizontal Starts -->
<input type="hidden" name="_token" value="{{csrf_token()}}">

<div class="form-group" ><!-- form-group Starts -->

<label class="col-md-3 control-label" >{{ __(' Product Category Title') }}</label>

<div class="controls col-md-6" >

<input type="text" name="p_cat_name" class="form-control @error('p_cat_name') is-invalid @enderror" value="{{ old('p_cat_name') }}" autofocus>

                @error('p_cat_name')
                                    <span class="invalid-feedback" role="alert" style="color:red">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
</div>

</div><!-- form-group Ends -->

<div class="form-group" ><!-- form-group Starts -->

<label class="col-md-3 control-label" >Show as Top Product Category</label>

<div class="controls col-md-6" >

<input type="radio" name="p_cat_top" value="yes" >

<label> Yes </label>

<input type="radio" name="p_cat_top" value="no" >

<label> No </label>

</div>

</div><!-- form-group Ends -->

<div class="form-group" ><!-- form-group Starts -->

<label class="col-md-3 control-label" > Select Product Category Image</label>

<div class="controls col-md-6" >

<input type="file" name="p_cat_image" class="form-control" >
<span class="text-danger" id="" style="color: red;">{{$errors->first('p_cat_image')}}</span>

</div>

</div><!-- form-group Ends -->

<div class="form-group" ><!-- form-group Starts -->

<label class="col-md-3 control-label" ></label>

<div class="controls col-md-6" >

<input type="submit" name="submit" value="Insert Product Category" class="btn btn-primary form-control" >

</div>

</div><!-- form-group Ends -->

</form><!-- form-horizontal Ends -->

</div><!-- panel-body Ends -->


</div><!-- panel panel-default Ends -->

</div><!-- col-lg-12 Ends -->

</div><!-- 2 row Ends -->




</div>

@endsection

resources/views/backEnd/productcategories/edit.blade.php
@extends('backEnd.layouts.master')
@section('title','Edit Product Category')
@section('content')

<div class="container">


<div class="row"><!-- 1 row Starts -->

<div class="col-lg-12"><!-- col-lg-12 Starts -->

<ol class="breadcrumb"><!-- breadcrumb Starts -->

<li>

<i class="fa fa-dashboard"></i> Dashboard / Edit Products Category

</li>

</ol><!-- breadcrumb Ends -->

</div><!-- col-lg-12 Ends -->

</div><!-- 1 row Ends -->

<div class="row"><!-- 2 row Starts -->

<div class="col-lg-12"><!-- col-lg-12 Starts -->

<div class="panel panel-default"><!-- panel panel-default Starts -->

<div class="panel-heading" ><!-- panel-heading Starts -->

<h3 class="panel-title" ><!-- panel-title Starts -->

<i class="fa fa-money fa-fw" ></i> Edit Product Category

</h3><!-- panel-title Ends -->


</div><!-- panel-heading Ends -->


<div class="panel-body" ><!-- panel-body Starts -->

<form class="form-horizontal" action="{{route('productcategory.update',$edit_p_cat->id)}}" method="post" enctype="multipart/form-data" ><!-- form-horizontal Starts -->

<input type="hidden" name="_token" value="{{csrf_token()}}">
{{method_field("PUT")}}
<div class="form-group" ><!-- form-group Starts -->

<label class="col-md-3 control-label" >Product Category Title</label>

<div class="controls col-md-6" >

<input type="text" name="p_cat_name" class="form-control" value="{{$edit_p_cat->p_cat_name}}" >

</div>

</div><!-- form-group Ends -->

<div class="form-group" ><!-- form-group Starts -->

<label class="col-md-3 control-label" >Show as Top Product Category</label>

<div class="controls col-md-6" >

<input type="radio" name="p_cat_top" value="yes"  {{ $edit_p_cat->p_cat_top == "yes" ? 'checked' : '' }} >

<label> Yes </label>

<input type="radio" name="p_cat_top" value="no"  {{ $edit_p_cat->p_cat_top == "no" ? 'checked' : '' }}  >

<label> No </label>

</div>

</div><!-- form-group Ends -->

<div class="form-group" ><!-- form-group Starts -->

<label class="col-md-3 control-label" > Select Product Category Image</label>

<div class="controls col-md-6" >

<input type="file" name="p_cat_image" class="form-control">
<img src="/storage/{{$edit_p_cat->p_cat_image}}" width="70" height="70" >

</div>

</div><!-- form-group Ends -->

<div class="form-group" ><!-- form-group Starts -->

<label class="col-md-3 control-label" ></label>

<div class="controls col-md-6" >

<input type="submit" name="submit" value="Update Product Category" class="btn btn-primary form-control" >

</div>

</div><!-- form-group Ends -->

</form><!-- form-horizontal Ends -->

</div><!-- panel-body Ends -->


</div><!-- panel panel-default Ends -->

</div><!-- col-lg-12 Ends -->

</div><!-- 2 row Ends -->




</div>

@endsection

resources/views/backEnd/productcategories/index.blade.php
@extends('backEnd.layouts.master')
@section('title','List Product Categories')
@section('content')

<div class="container">


<div class="row"><!-- 1 row Starts -->

<div class="col-lg-12"><!-- col-lg-12 Starts -->

<ol class="breadcrumb"><!-- breadcrumb Starts -->

<li class="active">

<i class="fa fa-dashboard"></i> Dashboard / View Products Categories

</li>

</ol><!-- breadcrumb Ends -->

</div><!-- col-lg-12 Ends -->

</div><!-- 1 row Ends -->


<div class="row"><!-- 2 row Starts -->

<div class="col-lg-12"><!-- col-lg-12 Starts -->

<div class="panel panel-default"><!-- panel panel-default Starts -->

<div class="panel-heading"><!-- panel-heading Starts -->

<h3 class="panel-title"><!-- panel-title Starts -->

<i class="fa fa-money fa-fw"> </i> View Products Categories

</h3><!-- panel-title Ends -->

</div><!-- panel-heading Ends -->

@if(Session::has('message'))
            <div class="alert alert-success text-center" role="alert">
                <strong>Well done!</strong> {{Session::get('message')}}
            </div>
        @endif
<div class="panel-body"><!-- panel-body Starts -->



<form class="navbar-form" method="post" action=""><!-- navbar-form Starts -->
<!-- {{csrf_field() }} -->
<div class="input-group"><!-- input-group Starts -->

<input class="form-control" type="text" placeholder="Search" name="product" placeholder="Keyword"  required>

<span class="input-group-btn"><!-- input-group-btn Starts -->

<button type="submit" value="Search" name="search" class="btn btn-primary">

<i class="fa fa-search"></i>

</button>

</span><!-- input-group-btn Ends -->

</div><!-- input-group Ends -->

</form><!-- navbar-form Ends -->







<div class="table-responsive"><!-- table-responsive Starts -->

<table class="table table-bordered table-hover table-striped"><!-- table table-bordered table-hover table-striped Starts -->

<thead><!-- thead Starts -->

<tr>

<th>Product Category Id</th>
<th>Product Category Title</th>
<th>Delete Product Category</th>
<th>Edit Product Category</th>


</tr>

</thead><!-- thead Ends -->

<tbody><!-- tbody Starts -->

@foreach($p_cats as $p_cat)


<tr>

<td> {{$p_cat->id}}</td>

<td> {{$p_cat->p_cat_name}} </td>


<td> 


<a href="javascript:" rel="{{$p_cat->id}}" rel1="delete-productcategory" class="btn-mini deleteRecord pull-left"> 
 <i class="fa fa-trash-o" > </i> Delete</a>

</td>

<td> 

<a href="{{route('productcategory.edit',$p_cat->id)}}" >

<i class="fa fa-pencil" ></i> Edit

</a>


</td>


</tr>

@endforeach

</tbody><!-- tbody Ends -->

</table><!-- table table-bordered table-hover table-striped Ends -->

</div><!-- table-responsive Ends -->

</div><!-- panel-body Ends -->

</div><!-- panel panel-default Ends -->

</div><!-- col-lg-12 Ends -->

</div><!-- 2 row Ends -->


</div>



@endsection

@section('jsblock')
<script src="{{asset('js/jquery.min.js')}}"></script>
    <script src="{{asset('js/jquery.ui.custom.js')}}"></script>
    <script src="{{asset('js/bootstrap.min.js')}}"></script>
    <script src="{{asset('js/jquery.uniform.js')}}"></script>
    <script src="{{asset('js/select2.min.js')}}"></script>
    <script src="{{asset('js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('js/matrix.js')}}"></script>
    <script src="{{asset('js/matrix.tables.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
<script>
        $(".deleteRecord").click(function () {
           var id=$(this).attr('rel');
           var deleteFunction=$(this).attr('rel1');
           swal({
               title:'Are you sure?',
               text:"You won't be able to revert this!",
               type:'warning',
               showCancelButton:true,
               confirmButtonColor:'#3085d6',
               cancelButtonColor:'#d33',
               confirmButtonText:'Yes, delete it!',
               cancelButtonText:'No, cancel!',
               confirmButtonClass:'btn btn-success',
               cancelButtonClass:'btn btn-danger',
               buttonsStyling:false,
               reverseButtons:true
           },function () {
              window.location.href="/admin/"+deleteFunction+"/"+id;
           });
        });
    </script>
@endsection