routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/////Start of Customer Location //////
//Front End homepage 
Route::get('/', 'IndexController@index')->name('home_page');
///About us page///
Route::get('/about', 'IndexController@about')->name('about');
//Service page
Route::get('/service', 'IndexController@service')->name('service_page');


////->middleware('verified')

////User Login and Register///
Auth::routes(['verify' => true]);
Route::get('/u/register', 'UsersController@create')->name('user_register');
Route::post('/u_register', 'UsersController@store',['verify' => true])->name('u_register')->middleware('verified');

Route::get('/u/login', 'UsersController@Index')->name('user_login');
Route::post('/u_login', 'UsersController@login',['verify' => true])->name('u_login');
Route::get('/u/logout', 'UsersController@logout')->name('user_logout');

// Route::match(['get','post'],'forget-password','UsersController@forgotPassword')->name('password.request');
//social login / facebook socialite
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider',['verify' => true]);
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

//social login with google socialite
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

//Shop Area////////////
Route::resource('/shop', 'ShopController');
Route::get('/product-detail/{id}','ShopController@detailproduct');
Route::get('/get-product-attr','ShopController@getAttrs');

///Search Product Area///
Route::post('/search','ShopController@search')->name('search');

/////Product Filter of Shop Sidebar////
Route::match(['get','post'],'/products-filter','ShopController@filterproduct');

//Get product Attribute price /////
Route::get('/get-product-price','ProductController@getProductPrice');
Route::get('/get-product-qty','ProductController@getProductQty');


//product review///
Route::post('/productReview','ProductReviewController@store')->name('productReview');


/////Cart Area /////
Route::post('/addToCart','CartController@addToCart')->name('addToCart');
Route::get('/viewcart','CartController@index');
Route::get('/resetCart','CartController@resetCart')->name('resetCart');
Route::get('/cart/update-quantity/{id}/{quantity}','CartController@updateQuantity');
Route::get('/cart/deleteItem/{id}','CartController@deleteItem');

//////Apply Coupon /////
Route::post('/cart/apply-coupon','CartController@applyCoupon');


Route::group(['middleware'=>['frontLogin']],function (){

    ////Customer Account Area //////
    Route::get('/account', 'UsersController@account')->name('user_account');
    Route::get('/update-profile', 'UsersController@edit')->name('update_profile');
    Route::post('/update-profile/{id}', 'UsersController@updateprofile')->name('update');
    Route::get('/u/update-password/', 'UsersController@showpassword')->name('change_p');
    Route::post('/update-password/{id}', 'UsersController@updatepassword')->name('update_p');

    //Wish list Area ////
    Route::get('/my-wish-list/', 'CartController@wishList')->name('wish_list');
    Route::get('/wish-list/delete-product/{id}','CartController@deleteWishListProducts');
    
    ///Contact Us Page ///
    Route::resource('/contact','ContactController');
    //Order Area///
    Route::get('/pay_offline', 'UsersController@payoffline')->name('pay_offline');
    Route::get('/check-out','CheckOutController@index');
    Route::post('/submit-checkout','CheckOutController@submitcheckout');
    Route::get('/order-review','OrderController@orderReview');
    Route::post('/submit-order','OrderController@order');
    Route::get('/cod','OrderController@cod');
    Route::get('/paypal','OrderController@paypal');
    Route::get('/pay','OrderController@pay');
    //paypal thanks page
    Route::get('/paypal/thanks','OrderController@thanksPaypal');
    //paypal cancel page
    Route::get('/paypal/cancel','OrderController@cancelPaypal');
    ////User Ordered Product Page
    Route::get('/orders/{id}','OrderController@userOrderDetails');
    

});


////End of Customer Location //////////


///////* Admin Location *///////
Auth::routes(['u_register'=>false,'verify'=>true]);
// Route::get('/home', 'HomeController@index')->name('home');
// Route::resource('admin/product','ProductController');

Route::group(['prefix'=>'admin','middleware'=>['auth','verified','checkAdmin']],function (){

    // Dashboard Area////
    Route::get('/', 'AdminController@index')->name('admin_home');
    Route::resource('/createuser', 'AdminController');
    Route::get('/showuser/', 'AdminController@showallusers')->name('show_user');
    Route::post('/showuser','AdminController@userSearch')->name('user.search');
    Route::get('/profile_update', 'AdminController@edit')->name('profile_update');
    Route::get('/order', 'OrderController@userOrder')->name('order');
    Route::post('/order', 'OrderController@searchOrder')->name('admin.search.order');

    //Admin Order Charts Route
    Route::get('/view-user-charts','AdminController@viewUserCharts');
    Route::get('delete-user/{id}','AdminController@destroy');

    ///Roles Area//////
    Route::resource('/role','RoleController');
    Route::resource('/roleuser','RoleUserController');

    
    
    
    //category Area
    Route::resource('/category','CategoryController');
    Route::get('delete-category/{id}','CategoryController@destroy');
    Route::get('/check_category_name','CategoryController@checkCateName');
    
    ///slider Area
    Route::resource('/slide','SlideController');
    Route::get('delete-slide/{id}','SlideController@destroy');
    Route::get('/check_slide_name','SlideController@checkSlideName');
    
    //Manufacturer or brands Area////
    Route::resource('/manufacturer','ManufacturerController');
    Route::get('delete-brand/{id}','ManufacturerController@destroy');
    
    //Product Category Area///
    Route::resource('/productcategory','ProductCategoryController');
    Route::get('delete-productcategory/{id}','ProductCategoryController@destroy');
    
    ///Box Section Area/////
    Route::resource('/box','BoxSectionController');
    Route::get('delete-box/{id}','BoxSectionController@destroy');
    
    ///Products Area///
    Route::resource('/product','ProductController');
    Route::get('delete-product/{id}','ProductController@destroy');
    Route::post('/products','ProductController@searchProducts')->name('product.search');
    
    
    ///Bundles Area///
    Route::get('/bundle','BundleController@create_bundle');
    Route::get('/bundles','BundleController@index');
    
    
    /// Product Attribute Area/////
    Route::resource('/product_attr','ProductAtrrController');
    Route::get('delete-attribute/{id}','ProductAtrrController@deleteAttr');
    
    /// Product Images Gallery///
    Route::resource('/image-gallery','ImagesController');
    Route::get('delete-imageGallery/{id}','ImagesController@destroy');
    
    ////Relation Area///
    Route::resource('/relation','RelationController');
    Route::get('delete-relation/{id}','RelationController@destroy');
    
    ///Coupon Area ////
    Route::resource('/coupon','CouponController');
    Route::get('delete-coupon/{id}','CouponController@destroy');
    
    ///View Orders Area////
    Route::resource('/orders','OrderController');
    Route::get('/admin/view-orders', 'OrderController@viewOrders');
    Route::get('/orders-invoice/{id}','OrderController@viewOrderInvoice')->name('order.invoice');
    Route::get('delete-order/{id}','OrderController@destroy');
    
    
    ///////Report Area /////// 
    Route::resource('/report','ReportController');
    Route::get('admin/reprot/show','ReportController@show');
    Route::get('/view-order-charts','ReportController@viewOrderCharts');
    Route::post('/report/check','ReportController@checkReport');

    ///Review Area/////
    Route::resource('/customer-reviews','ProductReviewController');
    Route::get('delete-customer-reviews/{id}','ProductReviewController@destroy');











    




});

resources/views/backEnd/layouts/footer.blade.php
<div class="row-fluid">
    <div id="footer" class="span12">Copyright ©2020 Anjit Shrestha. All rights reserved.</div>
</div>

resources/views/backEnd/layouts/header.blade.php
<!--Header-part-->

<div class="header">
    <h1><a href="dashboard.html">Dashboard</a></h1>
</div>
<!--close-Header-part-->
<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
    <ul class="nav">
        <li class=""><a title="" href="{{url('/admin/settings')}}"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
        <li class="">
            <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                <i class="icon icon-share-alt"></i>{{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>

        </li>
       
                       
                     
                   
    </ul>
  

            
                  
               
</div>
<!--close-top-Header-menu-->
<!--start-top-serch-->
<div id="search">
    <input type="text" placeholder="Search here..."/>
    <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
    
</div>

<!--close-top-serch-->

resources/views/backEnd/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@yield('title','Master Page')</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />

<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css.map" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{{asset('css/bootstraps.min.css')}}" />
    <link rel="stylesheet" href="{{asset('css/styles.css')}}" />
    <link rel="stylesheet" href="{{asset('css/bootstrap-responsive.min.css')}}" />
    <link rel="stylesheet" href="{{asset('css/colorpicker.css')}}" />
    <link rel="stylesheet" href="{{ asset('css/uniform.css') }}" />
    <link rel="stylesheet" href="{{ asset('css/select2.css') }}" />
    <link rel="stylesheet" href="{{asset('css/fullcalendar.css')}}" />
    <link rel="stylesheet" href="{{asset('css/matrix-style.css')}}" />
    <link rel="stylesheet" href="{{asset('css/matrix-media.css')}}" />
    <link rel="stylesheet" href="{{asset('css/bootstrap-wysihtml5.css')}}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">
    <link href="{{asset('font-awesome/css/font-awesome.css')}}" rel="stylesheet" />
    <link href="{{asset('font-awesome/css/css.css')}}" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="{{asset('css/jquery.gritter.css')}}" /> -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'> -->
    
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" /> -->

</head>
<body>


@include('backEnd.layouts.nav')
@include('backEnd.layouts.sidebar')

<!--main-container-part-->
<div id="content">
    @yield('content')
</div>
<!-- @include('backEnd.layouts.footer') -->

@yield('jsblock')



</body>
</html>

resources/views/backEnd/layouts/nav.blade.php
<div id="wrapper"><!-- wrapper Starts -->
<nav class="navbar navbar-inverse navbar-fixed-top" ><!-- navbar navbar-inverse navbar-fixed-top Starts -->

<div class="navbar-header" ><!-- navbar-header Starts -->

<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse" ><!-- navbar-ex1-collapse Starts -->


<span class="sr-only" >Toggle Navigation</span>

<span class="icon-bar" ></span>

<span class="icon-bar" ></span>

<span class="icon-bar" ></span>


</button><!-- navbar-ex1-collapse Ends -->

<a class="navbar-brand" href="" >Admin Panel</a>
<a class="navbar-brand" href="/" >Front End</a>


</div><!-- navbar-header Ends -->

<ul class="nav navbar-right top-nav" ><!-- nav navbar-right top-nav Starts -->

<li class="dropdown" ><!-- dropdown Starts -->

<a href="#" class="dropdown-toggle" data-toggle="dropdown" ><!-- dropdown-toggle Starts -->



@if(Auth::check())           
<i class="fa fa-user" >  {{ Auth::user()->name }}</i>
 @else
 <i class="fa fa-user" ></i>
 @endif

  <b class="caret" ></b>


</a><!-- dropdown-toggle Ends -->

<ul class="dropdown-menu" ><!-- dropdown-menu Starts -->

<li><!-- li Starts -->

<a href="{{route('profile_update')}}" >

<i class="fa fa-fw fa-user" ></i> Profile


</a>

</li><!-- li Ends -->

<li><!-- li Starts -->

<a href="{{route('product.index')}}" >

<i class="fa fa-fw fa-envelope" ></i> Products 

<span class="badge" ></span>


</a>

</li><!-- li Ends -->

<li><!-- li Starts -->

<a href="{{url('/admin/showuser')}}" >

<i class="fa fa-fw fa-gear" ></i> Customers

<span class="badge" ></span>


</a>

</li><!-- li Ends -->

<li><!-- li Starts -->

<a href="{{route('productcategory.index')}}" >

<i class="fa fa-fw fa-gear" ></i> Product Categories

<span class="badge" ></span>


</a>

</li><!-- li Ends -->

<li class="divider"></li>

<li><!-- li Starts -->


</li><!-- li Ends -->
<li class="submenu {{$menu_active ==5? ' active':''}}">
            <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                <i class="fa fa-fw fa-power-off"></i>{{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>

        </li>

</ul><!-- dropdown-menu Ends -->




</li><!-- dropdown Ends -->


</ul><!-- nav navbar-right top-nav Ends -->

resources/views/backEnd/layouts/navbar.blade.php
<!--sidebar-menu-->
<div id="sidebar"><a href="{{url('/admin')}}" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
    <ul>
        <li{{$menu_active==1? ' class=active':''}}><a href="{{url('/admin')}}"><i class="icon icon-home"></i> <span>Home</span></a> </li>
        <li class="submenu {{$menu_active==2? ' active':''}}"> <a href="#"><i class="icon icon-th-list"></i> <span>Categories</span></a>
            <ul>
                <li><a href="{{url('/admin/category/create')}}">Add New Category</a></li>
                <li><a href="{{route('category.index')}}">List Categories</a></li>
            </ul>
            
        </li>
        <li class="submenu {{$menu_active==3? ' active':''}}"> <a href="#"><i class="icon icon-th-list"></i> <span>Products</span></a>
            <ul>
                <li><a href="#">Add New Category</a></li>
                <li><a href="#">List Categories</a></li>
            </ul>
        </li>
        <li class="submenu {{$menu_active==3? ' active':''}}"> <a href="#"><i class="icon icon-th-list"></i> <span>Products</span></a>
            <ul>
                <li><a href="#">Add New Products</a></li>
                <li><a href="#">List Products</a></li>
            </ul>
        </li>
        <li class="submenu {{$menu_active==4? ' active':''}}"> <a href="#"><i class="icon icon-th-list"></i> <span>Coupons</span></a>
            <ul>
                <li><a href="">Add New Coupon</a></li>
                <li><a href="">List Coupons</a></li>
            </ul>
        </li>
        <li class="submenu {{$menu_active==5? ' active':''}}">
            <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                <i class="icon icon-share-alt"></i>{{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>

        </li>
    </ul>
</div>
<!--sidebar-menu-->

resources/views/backEnd/layouts/sidebar.blade.php
<div class="collapse navbar-collapse navbar-ex1-collapse"><!-- collapse navbar-collapse navbar-ex1-collapse Starts -->

<ul class="nav navbar-nav side-nav"><!-- nav navbar-nav side-nav Starts -->

        <li class=""><!-- li Starts -->

            <a href=" {{url('/admin')}}">

                <i class="fa fa-fw fa-dashboard"></i> Dashboard

            </a>

        </li><!-- li Ends -->

<li class=""><!-- Products li Starts -->

<a  href="" data-toggle="collapse" data-target="#products">

<i class="fa fa-fw fa-table"></i> Products

<i class="fa fa-fw fa-caret-down"></i>


</a>

<ul id="products" class="collapse">

<li>
<a href="{{url('/admin/product/create')}}"> Insert Products </a>
</li>

<li>
<a href="{{route('product.index')}}"> View Products </a>
</li>


</ul>

</li><!-- Products li Ends -->

<li class=""><!-- Bundles Li Starts --->

<a href="" data-toggle="collapse" data-target="#bundles">

<i class="fa fa-fw fa-edit"></i> Bundles

<i class="fa fa-fw fa-caret-down"></i>

</a>

<ul id="bundles" class="collapse">

<li>
<a href="{{url('/admin/bundle')}}"> Insert Bundle </a>
</li>

<li>
<a href="{{url('/admin/bundles')}}"> View Bundles </a>
</li>

</ul>

</li><!-- Bundles Li Ends --->

<li><!-- relations li Starts -->

<a href="#" data-toggle="collapse" data-target="#relations"><!-- anchor Starts -->

<i class="fa fa-fw fa-retweet"></i> Assign Products To Bundles Relations

<i class="fa fa-fw fa-caret-down"></i>

</a><!-- anchor Ends -->

<ul id="relations" class="collapse"><!-- collapse Starts -->

<li>

<a href="{{url('/admin/relation/create')}}"> Insert Relation </a>

</li>


<li>

<a href="{{route('relation.index')}}"> View Relations </a>

</li>

</ul><!-- collapse Ends -->


</li><!-- relations li Ends -->



<li><!-- manufacturer li Starts -->

<a href="#" data-toggle="collapse" data-target="#manufacturers"><!-- anchor Starts -->

<i class="fa fa-fw fa-briefcase"></i> Manufacturers

<i class="fa fa-fw fa-caret-down"></i>


</a><!-- anchor Ends -->

<ul id="manufacturers" class="collapse"><!-- ul collapse Starts -->

<li>
<a href="{{url('/admin/manufacturer/create')}}"> Insert Manufacturer </a>
</li>

<li>
<a href="{{route('manufacturer.index')}}"> View Manufacturers </a>
</li>

</ul><!-- ul collapse Ends -->


</li><!-- manufacturer li Ends -->


<li><!-- li Starts -->

<a href="#" data-toggle="collapse" data-target="#p_cat">

<i class="fa fa-fw fa-pencil"></i> Products Categories

<i class="fa fa-fw fa-caret-down"></i>


</a>

<ul id="p_cat" class="collapse">

<li>
<a href="{{url('/admin/productcategory/create')}}"> Insert Product Category </a>
</li>

<li>
<a href="{{route('productcategory.index')}}"> View Products Categories </a>
</li>


</ul>

</li><!-- li Ends -->


<li><!-- li Starts -->

<a href="#" data-toggle="collapse" data-target="#cat">

<i class="fa fa-fw fa-arrows-v"></i> Categories

<i class="fa fa-fw fa-caret-down"></i>

</a>

<ul id="cat" class="collapse">

<li>
<a href="{{url('/admin/category/create')}}"> Insert Category </a>
</li>

<li>
<a href="{{route('category.index')}}"> View Categories </a>
</li>


</ul>

</li><!-- li Ends -->


<li><!-- boxes section li Starts -->

<a href="#" data-toggle="collapse" data-target="#boxes"><!-- anchor Starts -->

<i class="fa fa-fw fa-arrows"></i> Boxes Section

<i class="fa fa-fw fa-caret-down"></i>

</a><!-- anchor Ends -->

<ul id="boxes" class="collapse">

<li>

<a href="{{url('/admin/box/create')}}"> Insert Box </a>

</li>


<li>

<a href="{{route('box.index')}}"> View Boxes </a>

</li>

</ul>

</li><!--boxes section li Ends -->

<!-- services section li Starts -->
<!-- <li>

<a href="#" data-toggle="collapse" data-target="#services">

<i class="fa fa-fw fa-briefcase"></i> Services

<i class="fa fa-fw fa-caret-down"></i>

</a>

<ul id="services" class="collapse">

<li>
<a href=""> Insert Service </a>
</li>

<li>
<a href=""> View Services </a>
</li>

</ul>

</li> -->
<!-- services section li Ends -->


<!-- contact us li Starts -->
<!-- <li>

<a href="#" data-toggle="collapse" data-target="#contact_us">


<i class="fa fa-fw fa-pencil"> </i> Contact Us Section

<i class="fa fa-fw fa-caret-down"></i>

</a> -->
<!-- anchor Ends -->
<!-- 
<ul id="contact_us" class="collapse">

<li>

<a href=""> Edit Contact Us </a>

</li>

<li>

<a href=""> Insert Enquiry Type </a>

</li>

<li>

<a href=""> View Enquiry Types </a>

</li>

</ul> -->

<!-- </li> -->
<!-- contact us li Ends -->

<!-- <li> -->
<!-- about us li Starts -->

<!-- <a href="">

<i class="fa fa-fw fa-edit"></i> Edit About Us Page

</a>

</li> -->
<!-- about us li Ends -->


<li><!-- Coupons Section li Starts -->

<a href="#" data-toggle="collapse" data-target="#coupons"><!-- anchor Starts -->

<i class="fa fa-fw fa-arrows-v"></i> Coupons

<i class="fa fa-fw fa-caret-down"></i>

</a><!-- anchor Ends -->

<ul id="coupons" class="collapse"><!-- ul collapse Starts -->

<li>
<a href="{{url('/admin/coupon/create')}}"> Insert Coupon </a>
</li>

<li>
<a href="{{route('coupon.index')}}"> View Coupons </a>
</li>

</ul><!-- ul collapse Ends -->

</li><!-- Coupons Section li Ends -->

<li><!-- slide li Starts -->

<a href="#" data-toggle="collapse" data-target="#slides">

<i class="fa fa-fw fa-gear"></i> Slides

<i class="fa fa-fw fa-caret-down"></i>


</a>

<ul id="slides" class="collapse">

<li>
<a href="{{url('/admin/slide/create')}}"> Insert Slide </a>
</li>

<li>
<a href="{{route('slide.index')}}"> View Slides </a>
</li>


</ul>

<!-- slide li Ends -->
</li>

<!-- terms li Starts -->

<li>

<a href="{{url('/admin/showuser')}}">

<i class="fa fa-fw fa-edit"></i> View Customers

</a>

</li>




<li><!-- terms li Starts -->

<a href="#" data-toggle="collapse" data-target="#reports" ><!-- anchor Starts -->

<i class="fa fa-fw fa-table"></i> Reports

<i class="fa fa-fw fa-caret-down"></i>

</a><!-- anchor Ends -->

<ul id="reports" class="collapse"><!-- ul collapse Starts -->



<li>
<a href="{{route('report.index')}}"> View Report </a> 
</li>

<li>

<a href="{{route('order')}}">

<i class="fa fa-fw fa-list"></i> View Orders

</a>

</li>
<li>

<a href="{{url('admin/view-order-charts')}}">

<i class="fa fa-fw fa-edit"></i> Order Report Chart

</a>

</li>

</ul><!-- ul collapse Ends -->


</li><!-- terms li Ends -->


<li>

<a href="{{route('customer-reviews.index')}}">

<i class="fa fa-fw fa-pencil"></i> Manage Reviews

</a>

</li>

<li><!-- li Starts -->

<a href="#" data-toggle="collapse" data-target="#users">

<i class="fa fa-fw fa-gear"></i> Users

<i class="fa fa-fw fa-caret-down"></i>


</a>

<ul id="users" class="collapse">

<li>
<a href="{{url('/admin/createuser/create')}}"> Insert User </a>
</li>

<li>
<a href="{{url('/admin/showuser')}}"> Show Users </a>
</li>


<li>
<a href="{{url('/admin/role/create')}}"> Insert Roles </a>
</li>

<li>
<a href="{{url('/admin/roleuser/create')}}"> Insert User Roles </a>
</li>
<li>
<a href="{{url('admin/view-user-charts')}}"> User Register Charts </a>
</li>

</ul>

</li><!-- li Ends -->

<li><!-- li Starts -->

<li class="">
            <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                <i class="fa fa-fw fa-power-off"></i>{{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>

        </li>

</li><!-- li Ends -->

</ul><!-- nav navbar-nav side-nav Ends -->

</div><!-- collapse navbar-collapse navbar-ex1-collapse Ends -->

</nav><!-- navbar navbar-inverse navbar-fixed-top Ends -->
<div id="page-wrapper"><!-- page-wrapper Starts -->



</div><!-- page-wrapper Ends -->

</div><!-- wrapper Ends -->